version: '3.8'
services:
    laravel:
        build: 
            context: .
            dockerfile: php.Dockerfile
        ports:
            - "127.0.0.1:8000:8000"
        depends_on:
            - db
    
    db:
        build: 
            context: .
            dockerfile: postgres.Dockerfile
        restart: unless-stopped
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"    
        

    